In [10]:
from datalibweb import datalibweb
dw = datalibweb()

In [11]:
files = dw.getFileCollection('ECA', 'ALB', '2008','ECAPOV', latest=False)

Field Query String : Server=ECA&Country=ALB&Year=2008&Collection=ECAPOV

In [13]:
indfilerecords1 =  dw.getRecords(server='ECA', countries= ['ALB'], 
                                 years= ['2008'], 
                                 collection= 'ECAPOV', 
                                 modules=['2','6'],
                                 minorversion=6, majorversion=1, latest=False)

Field Query String : Server=ECA&Country=ALB&Year=2008&Collection=ECAPOV
Field Query String : Server=ECA&Country=ALB&Year=2008&Para1=\ALB\ALB_2008_LSMS\ALB_2008_LSMS_v01_M_v06_A_ECAPOV\Data\Harmonized\ALB_2008_LSMS_v01_M_v06_A_ECAPOV_2.dta&Collection=ECAPOV

In [14]:
indfilerecords1

,countrycode,year,ref_year,survey_year,hhid,pid,weight,strata,psu,quarter,...,lfstat,minlaborage,empstat,industrycat10,industrycat4,sector_w,sector_a,type_contract,empl_time,occup
0,ALB,2008,2008,2008,101,1,367.931549,NaN,1,NaN,...,Retired,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALB,2008,2008,2008,101,2,367.931549,NaN,1,NaN,...,Self Employed,16,Self-employed,NaN,NaN,NaN,NaN,NaN,Full-time,NaN
2,ALB,2008,2008,2008,101,3,367.931549,NaN,1,NaN,...,Employee,16,Non-paid employee/family worker,NaN,NaN,NaN,NaN,NaN,Full-time,NaN
3,ALB,2008,2008,2008,101,4,367.931549,NaN,1,NaN,...,Student,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ALB,2008,2008,2008,101,5,367.931549,NaN,1,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ALB,2008,2008,2008,101,6,367.931549,NaN,1,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ALB,2008,2008,2008,102,1,367.931580,NaN,1,NaN,...,Self Employed,16,Self-employed,NaN,NaN,NaN,NaN,NaN,Full-time,NaN
7,ALB,2008,2008,2008,102,2,367.931580,NaN,1,NaN,...,Employee,16,Non-paid employee/family worker,NaN,NaN,NaN,NaN,NaN,Part-time,NaN
8,ALB,2008,2008,2008,102,3,367.931580,NaN,1,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,ALB,2008,2008,2008,102,4,367.931580,NaN,1,NaN,...,Retired,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,ALB,2008,2008,2008,102,5,367.931580,NaN,1,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,ALB,2008,2008,2008,103,1,367.931549,NaN,1,NaN,...,Retired,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,ALB,2008,2008,2008,103,2,367.931549,NaN,1,NaN,...,Retired,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,ALB,2008,2008,2008,103,3,367.931549,NaN,1,NaN,...,Employee,16,Non-paid employee/family worker,NaN,NaN,NaN,NaN,NaN,Full-time,NaN
14,ALB,2008,2008,2008,104,1,367.931549,NaN,1,NaN,...,Employee,16,Non-paid employee/family worker,NaN,NaN,NaN,NaN,NaN,Full-time,NaN
15,ALB,2008,2008,2008,104,2,367.931549,NaN,1,NaN,...,Employee,16,Non-paid employee/family worker,NaN,NaN,NaN,NaN,NaN,Part-time,NaN
16,ALB,2008,2008,2008,104,3,367.931549,NaN,1,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,ALB,2008,2008,2008,104,4,367.931549,NaN,1,NaN,...,Employee,16,Non-paid employee/family worker,NaN,NaN,NaN,NaN,NaN,Part-time,NaN
18,ALB,2008,2008,2008,105,1,367.931549,NaN,1,NaN,...,Employee,16,Non-paid employee/family worker,NaN,NaN,NaN,NaN,NaN,Part-time,NaN
19,ALB,2008,2008,2008,105,2,367.931549,NaN,1,NaN,...,Employee,16,Non-paid employee/family worker,NaN,NaN,NaN,NaN,NaN,Full-time,NaN
20,ALB,2008,2008,2008,105,3,367.931549,NaN,1,NaN,...,Employee,16,Non-paid employee/family worker,NaN,NaN,NaN,NaN,NaN,Part-time,NaN
21,ALB,2008,2008,2008,105,4,367.931549,NaN,1,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,ALB,2008,2008,2008,105,5,367.931549,NaN,1,NaN,...,OLF,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,ALB,2008,2008,2008,105,6,367.931549,NaN,1,NaN,...,Retired,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,ALB,2008,2008,2008,106,1,367.931549,NaN,1,NaN,...,OLF,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,ALB,2008,2008,2008,106,2,367.931549,NaN,1,NaN,...,Employee,16,Non-paid employee/family worker,NaN,NaN,NaN,NaN,NaN,Part-time,NaN
26,ALB,2008,2008,2008,106,3,367.931549,NaN,1,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,ALB,2008,2008,2008,106,4,367.931549,NaN,1,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,ALB,2008,2008,2008,106,5,367.931549,NaN,1,NaN,...,Employee,16,Non-paid employee/family worker,NaN,NaN,NaN,NaN,NaN,Part-time,NaN
29,ALB,2008,2008,2008,107,1,367.931549,NaN,1,NaN,...,Self Employed,16,Self-employed,NaN,NaN,NaN,NaN,NaN,Full-time,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14839,ALB,2008,2008,2008,45002,11,319.534607,NaN,450,NaN,...,Self Employed,16,Self-employed,NaN,NaN,NaN,NaN,NaN,Full-time,NaN
14840,ALB,2008,2008,2008,45003,1,319.534607,NaN,450,NaN,...,Employee,16,Paid employee,NaN,NaN,Private,NaN,NaN,Full-time,NaN
14841,ALB,2008,2008,2008,45003,2,319.534607,NaN,450,NaN,...,OLF,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14842,ALB,2008,2008,2008,45003,3,319.534607,NaN,450,NaN,...,Employee,16,Paid employee,NaN,NaN,Private,NaN,NaN,Part-time,NaN
14843,ALB,2008,2008,2008,45003,4,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14844,ALB,2008,2008,2008,45003,5,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14845,ALB,2008,2008,2008,45003,6,319.534607,NaN,450,NaN,...,Retired,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14846,ALB,2008,2008,2008,45004,1,319.534607,NaN,450,NaN,...,Employee,16,Paid employee,NaN,NaN,Private,NaN,NaN,Full-time,NaN
14847,ALB,2008,2008,2008,45004,2,319.534607,NaN,450,NaN,...,Employee,16,Paid employee,NaN,NaN,Private,NaN,NaN,Part-time,NaN
14848,ALB,2008,2008,2008,45004,3,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14849,ALB,2008,2008,2008,45005,1,319.534607,NaN,450,NaN,...,OLF,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14850,ALB,2008,2008,2008,45005,2,319.534607,NaN,450,NaN,...,OLF,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14851,ALB,2008,2008,2008,45005,3,319.534607,NaN,450,NaN,...,Student,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14852,ALB,2008,2008,2008,45005,4,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14853,ALB,2008,2008,2008,45005,5,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14854,ALB,2008,2008,2008,45006,1,319.534607,NaN,450,NaN,...,Self Employed,16,Self-employed,NaN,NaN,NaN,NaN,NaN,Part-time,NaN
14855,ALB,2008,2008,2008,45006,2,319.534607,NaN,450,NaN,...,OLF,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14856,ALB,2008,2008,2008,45006,3,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14857,ALB,2008,2008,2008,45006,4,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14858,ALB,2008,2008,2008,45007,1,319.534607,NaN,450,NaN,...,Employee,16,Paid employee,NaN,NaN,Private,NaN,NaN,Full-time,NaN
14859,ALB,2008,2008,2008,45007,2,319.534607,NaN,450,NaN,...,OLF,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14860,ALB,2008,2008,2008,45007,3,319.534607,NaN,450,NaN,...,OLF,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14861,ALB,2008,2008,2008,45007,4,319.534607,NaN,450,NaN,...,OLF,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14862,ALB,2008,2008,2008,45007,5,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14863,ALB,2008,2008,2008,45007,6,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14864,ALB,2008,2008,2008,45008,1,319.534607,NaN,450,NaN,...,Unemployed,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14865,ALB,2008,2008,2008,45008,2,319.534607,NaN,450,NaN,...,OLF,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14866,ALB,2008,2008,2008,45008,3,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14867,ALB,2008,2008,2008,45008,4,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14868,ALB,2008,2008,2008,45008,5,319.534607,NaN,450,NaN,...,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
indfilerecords1.agg({'weight' : ['sum','min']})

           weight
sum  3.168282e+06
min  1.797268e+01